In [41]:
import numpy as np


In [42]:
arr= np.array([1,2,3,4,5])  #1d array
arr.ndim                    # ndim checks the dimension of array

1

In [43]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])  #2d array
arr2.ndim


2

In [44]:
arr3 = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])  #3 array
arr3.ndim

3

In [45]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr3 = np.concatenate((arr1 , arr2),axis=1)
arr3


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:
type(arr2)      #gives the type of arr2



numpy.ndarray

In [47]:
arr2.dtype          #gives the type of data inside arr2

dtype('int32')

In [48]:
arr=[[1,2,3,4,5],[1,2,3,4,5],
                [1,2,3,4,5],[1,2,3,4,5]]

arr1 = np.array_split(arr,4)    #split array in 4 parts
arr1

[array([[1, 2, 3, 4, 5]]),
 array([[1, 2, 3, 4, 5]]),
 array([[1, 2, 3, 4, 5]]),
 array([[1, 2, 3, 4, 5]])]

In [49]:
m= np.array(arr)
n = m.flatten()     # make 1d array 
n

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [50]:
k = np.unique(m)    #remove all duplicate data
k

array([1, 2, 3, 4, 5])

In [51]:
m

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [52]:
delete_data = np.delete(m,2,axis=1) #delete the 3rd column of the data ie 3
delete_data

array([[1, 2, 4, 5],
       [1, 2, 4, 5],
       [1, 2, 4, 5],
       [1, 2, 4, 5]])

In [53]:
delete_data = np.delete(m,2,axis=0)     # delete the 3rd row
delete_data

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [54]:
m.shape #gives the shape ie.(2, 3), meaning the array has 2 rows and 3 columns.
        #(2, 2, 2), indicating the array has 2 blocks, each containing 2 rows and 2 columns.

(4, 5)

In [55]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4]])


In [57]:
c = a*2             #gives the multiplication of a and 2
d = np.dot(b,b)     #gives the matrix multlipication of b and b
c,d

(array([2, 4, 6, 8]),
 array([[ 7, 10],
        [15, 22]]))

In [60]:
mean_a = np.mean(a)     #gives the mean of a
std_a = np.std(a)       #gives the standard deviation of a

mean_a ,std_a

(2.5, 1.118033988749895)

In [64]:
eigen_value,eigen_vectors = np.linalg.eig(b)
eigen_value,eigen_vectors

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [66]:
random_numbers = np.random.rand(5)
random_numbers

array([0.03592999, 0.53472768, 0.71858756, 0.98874598, 0.77912784])

In [67]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [70]:
identity_matrix = np.eye(3)     #gives identity matrix of given parameter
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])